export const DoctorData = [
  {
    username: 'arben.hoxha',
    full_name: 'Dr. Arben Hoxha',
    age: 45,
    email: 'arben.hoxha@example.com',
    specialization: 'gastroenterologji',
    phone: '+355 69 123 4567',
    experience: '20 vite eksperiencë në kirurgji të përgjithshme',
    gender: 'Mashkull',
    location: 'Tiranë, Shqipëri',
    biography: 'Dr. Arben Hoxha ka punuar në disa spitale të njohura dhe ka një eksperiencë të gjerë në kirurgji.',
  },
  {
    username: 'elira.dervishi',
    full_name: 'Dr. Elira Dervishi',
    age: 38,
    email: 'elira.dervishi@example.com',
    specialization: 'Stomatologji',
    phone: '+355 69 234 5678',
    experience: '15 vite eksperiencë në stomatologji pediatrike dhe estetike',
    gender: 'Femer',
    location: 'Durrës, Shqipëri',
    biography: 'Dr. Elira Dervishi fokusohet në shëndetin oral dhe estetikën e dhëmbëve të pacientëve të saj.',
  },
  {
    username: 'gentian.kola',
    full_name: 'Dr. Gentian Kola',
    age: 50,
    email: 'gentian.kola@example.com',
    specialization: 'Kardiologji',
    phone: '+355 69 345 6789',
    experience: '25 vite eksperiencë në kardiologji dhe trajtime të avancuara të zemrës',
    gender: 'Mashkull',
    location: 'Vlorë, Shqipëri',
    biography: 'Dr. Gentian Kola ka specializim në trajtime të avancuara kardiake dhe ndjek pacientët me kujdes të veçantë.',
  },
];
